# Change these first
owner: ryanfitton # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: ryanfitton.co.uk
    url: https://ryanfitton.co.uk
  - name: ryanfitton.co.uk/blog/
    url: https://ryanfitton.co.uk/blog/
  - name: ryanfitton.co.uk/portfolio/
    url: https://ryanfitton.co.uk/portfolio/
  - name: ryanfitton-nextjs-2024.ryanfitton.co.uk
    url: https://ryanfitton-nextjs-2024.ryanfitton.co.uk

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ryanfitton.co.uk
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/ryanfitton/upptime/master/assets/logo-small.png
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: About
      href: https://ryanfitton.co.uk/about/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
